// Bộ icon dùng chung - dùng Polaris Icons (@shopify/polaris-icons) để đồng bộ
// style với giao diện Polaris. Mọi icon là vector SVG (xem docs/UI-GUIDELINES.md).
// Re-export dưới tên quen thuộc trong app; alias vài icon sang tên Polaris tương ứng.
export {
  HomeIcon,
  SearchIcon,
  EditIcon,
  TargetIcon,
  UploadIcon,
  CalendarIcon,
  LinkIcon,
  SettingsIcon,
  PlusIcon,
  ArrowRightIcon,
  CheckIcon,
  XIcon,
  ImageIcon,
  NoteIcon,
  GlobeIcon,
  MagicIcon,
  PersonIcon,
  EmailIcon,
  ExitIcon,
  StoreIcon,
  KeyIcon,
  ListBulletedIcon as ListIcon,
  LanguageTranslateIcon as TranslateIcon,
  ChartVerticalIcon as BarsIcon,
  AlertTriangleIcon as AlertIcon,
  ReplaceIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  PageIcon,
  NotificationIcon,
  MegaphoneIcon,
  ClipboardIcon,
  PlayCircleIcon,
  QuestionCircleIcon as HelpIcon,
} from '@shopify/polaris-icons';
